-- seed/seed.sql
-- The Phase-0 connectivity-smoke fixture (one `restaurants` row) was removed in Phase 1 along
-- with its permissive read policy and anon grant (migration 0007_drop_phase0_smoke.sql).
-- Restaurants are now populated per-session from the provider (Phase 2), never seeded — they
-- are not a permanent local mirror of provider data (CLAUDE.md §3). Intentionally empty.
